### ISSUE TITLE
Device Count 0

### ISSUE THREAD

**Issue by tgb20** [getoffmyhack/waveSDR#1]
I am currently working on my own SDR client for ADBS use and found your project, I see yours is working, but mine does not. I was wondering if you could offer any technical advice mainly getting the RTL-SDR library to recognize connected devices. I have successfully wrapped it for swift, but when testing it always returns 0 devices, whiles yours can successfully find and detect my device. Thanks. You can see my repo here, its a little simple because of this roadblock. https://github.com/tgb20/newtSDR/tree/master

**Comment by getoffmyhack** [comment]
Hello Jacob,

I downloaded your project, compiled it on my machine, ran it, and it came back with the number of devices I have connected.  I tried it with 0, 1, 2, and 3 different RTL-SDRs and it worked properly in all cases.  From a code standpoint, you have everything working.

As to why it’s not working for you, that is hard to say.  What I can recommend is that you make sure the the librtlsdr command line tools work first.  The easiest way is to just use the rtl_test program:

[MBPro:~] justin% rtl_test
Found 1 device(s):
  0:  Generic, RTL2832U, SN: 77771111153705700

Using device 0: Generic RTL2832U
Found Rafael Micro R820T tuner
Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6
Sampling at 2048000 S/s.

Info: This tool will continuously read from the device, and report if
samples get lost. If you observe no further output, everything is fine.

Reading samples in async mode...
^CSignal caught, exiting!

User cancel, exiting...
Samples per million lost (minimum): 0
[MBPro:~] justin%

For what it’s worth, I used MacPorts (https://www.macports.org/ <https://www.macports.org/>) to initially install and test the RTL-SDR lib and command line tools.  Once I was comfortable with that, I have since started to use the https://github.com/steve-m/librtlsdr <https://github.com/steve-m/librtlsdr> repo directly.

Let me know if there is anything else.


Justin

**Comment by tgb20** [comment]
I just installed and tested the RTL-SDR command line tools and they work, detecting my device. What is odd to me is that when I run your program, even before I had the command line tools, it worked. Its just my specific Xcode project that doesn't. And when you run my program it works for you.

Jacob

**Comment by getoffmyhack** [comment]
Sorry, one thing I should have pointed out, and with this build warning, it may be related to your issue;  I don’t have an Apple developer’s account so I turned off code signing in order to compile the code (it wouldn’t compile without it). This is the compiler warning:

Code Signing Warning: "newtSDR" isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it.

Try turning off code signing and see where that gets you.  Since waveSDR is my first real macOS desktop application, and is a hobby project at that, I am not familiar enough with the macOS application build options to provide much more help.

Hope that bit of info helps.

Justin

**Comment by tgb20** [comment]
It wouldn't be the code signing but I disabled the Entitlements and it worked. Thanks for working with me and leading me to the solution. Seems I had set the app to run in a Sandbox and it locked out all connections to the computer. Not sure where I did that, but now its fixed.

Thanks Jacob
