### ISSUE TITLE
HackRF One Support

### ISSUE THREAD

**Issue by Dygear** [getoffmyhack/waveSDR#2]
I plugged in my HackRF and lunched waveSDR. In the devices list it shows no devices found. I plugged in my RTL Dongle, and that did correctly show an RTL Device. Can you please add support for the HackRF?

Also, I _LOVE_ this project, I would love to support it by sending you some hardware. I am willing to buy and send you a HackRF as a donation for making this software. It's AMAZING and exactly what I was looking for when it comes to learning Swift with the RTL Software Library. (Also really love what your doing the the [RTLSDR.Swift](https://github.com/getoffmyhack/RTLSDR.Swift) project. That's amazing too!) I've signed up for your Wordpress site, using my actual email address. Please tell me where I should send the HackRF to!

**Comment by getoffmyhack** [comment]
Hi Mark,

Thanks for reaching out to me.  It’s always exciting for me to hear from somebody using my program.  Anyway, I didn’t realize until this morning that I had my Wordpress site in private mode, but that has been cleared up.

I have always planned on adding support for different SDR hardware, and the code has been abstracted enough by design to allow for doing just that.  Therefore, it shouldn’t be too difficult to add a new hardware device.

As to discussing the HackRF, I will send an email to your address listed on your Github profile page (let me know if there is something better to use) and we can continue this “off-list”. 

Again, thanks for reaching out to me!

Justin
