### ISSUE TITLE
Re-arrange values

### ISSUE THREAD

**Issue by davorinm** [getoffmyhack/waveSDR#3]
Hi Justin,

I’m developing similar SDR app than waveSDR (for which i think is absolutely awesome) and i could not get proper fft output. I’m using function vDSP_DFT_Execute. I noticed that output is in some way shifted between left and right half.

I did see that you rearrange output values to correct this:
https://github.com/getoffmyhack/waveSDR/blob/861d5bdcfa0860993efda530a894b00cec51a36d/waveSDR/SDR/DSP/FFTBlock.swift#L118

Do you know why is this needed in first place? 

Thank you!

**Comment by getoffmyhack** [comment]
The last time I had to implement my own FFT algorithm was back in university, so I don’t quite remember the exact reason why it’s happening, but I can tell you what is happening.  Basically it’s an artifact of how the FFT operates and this is a very broad overview of what’s happening.

The first half of the FFT results contain the frequency spectra of the real components, or positive frequencies, of the time domain signal where the second half of the FFT results contain the frequency spectra of the imaginary components, or negative frequencies.

When using a real signal with zero-stuffed imaginary components, the frequency spectra of the imaginary components of the time domain signal is just an exact mirror of the frequency spectra of the real components and essentially has no use.

When using a true complex signal, such as the IQ data from an SDR, the frequency spectra of the real components are the positive frequencies from Fc —> +Fs/2 and the frequency spectra of the imaginary components are the negative frequencies from -Fs/2 —> Fc  where Fc = center frequency and Fs is the sample rate.  Therefore, in order to get the proper spectrum view, the negative frequencies need to be placed in front of the positive frequencies giving you -Fs/2 —> Fc —> +Fs/2

https://www.dspguide.com/ <https://www.dspguide.com/> is a great book, even though it’s free online, I bought the hard cover because I find it very useful when I need to give myself a refresher on DSP topics.  Chapter 12 has a great discussion on the FFT and will provide a much better and more in-depth explanation that I can.

Hope this helps you better understand what is happening.

Thanks,

Justin

**Comment by getoffmyhack** [comment]
I should also add a caveat, as it's been quite some time since I have been working on DSP code, I may be a bit hazy and could be a bit off in areas of my explanation, but the general overview should still be correct.
